In [56]:
import numpy as np
import pandas as pd

In [57]:
np.random.seed(42) # 42 koi special mathematical number nahi hai. Ye sirf reproducibility ke liye random seed hai.
n=200

In [58]:
#Student weekly kitne hours study karta hai:
study_hours=np.random.randint(2,19, size=n)
study_hours[:10]

array([ 8, 16, 12,  9,  8, 12, 12,  5,  9,  4], dtype=int32)

In [59]:
attendance=np.random.randint(50,101,size=n)  #50 ≤ attendance ≤ 100
attendance[:10]

array([68, 97, 65, 52, 69, 73, 82, 73, 60, 98], dtype=int32)

In [60]:
#Student group discussion mein participate karta hai ya nahi
group_discussion=np.random.choice(['yes','no'], size=n, p=[0.7,0.3])
group_discussion[:10]

array(['yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'no', 'yes', 'yes', 'no'],
      dtype='<U3')

In [61]:
#Previous internal test ke marks
previous_test_score=np.random.randint(30,101,size=n)
previous_test_score[:10]

array([98, 34, 32, 82, 52, 82, 66, 46, 30, 80], dtype=int32)

In [62]:
#study hours, attendance aur previous score ko consider karenge.
final_score = (
    0.4 * study_hours +
    0.3 * attendance +
    0.3 * previous_test_score
)

In [63]:
final_exam_pass = np.where(
    final_score >= 60,
    "Pass",
    "Fail"
)   
#calculated score ≥ 60 → Pass
#calculated score < 60 → Fail

In [64]:
#columns combinations
df = pd.DataFrame({
    "Student_ID": range(1, n + 1),
    "study_hours": study_hours,
    "attendance": attendance,
    "group_discussion": group_discussion,
    "previous_test_score": previous_test_score,
    "final_exam_pass": final_exam_pass
})

In [65]:
#check
df.head()

,Student_ID,study_hours,attendance,group_discussion,previous_test_score,final_exam_pass
0,1,8,68,yes,98,Fail
1,2,16,97,yes,34,Fail
2,3,12,65,yes,32,Fail
3,4,9,52,yes,82,Fail
4,5,8,69,yes,52,Fail

In [66]:
df.to_csv("students_data.csv", index=False)

# 1. Understanding the Basics

## What is Probability?

Probability is a measure of how likely an event is to occur.

It ranges from 0 to 1:

- 0 → Impossible event
- 0.25 → Low chance
- 0.50 → 50-50 chance
- 0.75 → High chance
- 1 → Certain event

Formula:

P(E) = Favourable Outcomes / Total Outcomes

## Key Probability Terminology

- Experiment: A process that produces an outcome.
- Outcome: A possible result of an experiment.
- Sample Space: The set of all possible outcomes.
- Event: A specific outcome or group of outcomes of interest.
- Favourable Outcome: An outcome that satisfies the condition of an event.
- Probability: The numerical measure of the chance that an event occurs.

### Probability Events from the Dataset

We consider the following events:

1. Event A: A randomly selected student passes the final exam.
2. Event B: A randomly selected student has attendance greater than 80%.
3. Event C: A randomly selected student participates in group discussion.

#### 1. Event A: A randomly selected student passes the final exam.

In [67]:
total_students=len(df)

pass_students=(df["final_exam_pass"]=="Pass").sum()

p_pass=pass_students / total_students 

print("p(pass)=", p_pass)

p(pass)= 0.035

#### 2. Event B: A randomly selected student has attendance greater than 80%.

In [68]:
high_attendance = (df["attendance"] > 80).sum()
p_high_attendance = high_attendance / total_students
print("P(Attendance > 80%)=",p_high_attendance)

P(Attendance > 80%)= 0.435

#### 3. Event C: A randomly selected student participates in group discussion.

In [69]:
group_discussion_yes= (df["group_discussion"]== "yes").sum()
p_group_discussion = group_discussion_yes / total_students
print("P(Group Discussion = Yes)=", p_group_discussion)

P(Group Discussion = Yes)= 0.715

#### Percenatage

In [70]:
print("p(pass)=", round(p_pass*100,2),"%")
print("P(Attendance > 80%)=",round(p_high_attendance *100,2),"%")
print("P(Group Discussion = Yes)=", round(p_group_discussion * 100,2),"%")

p(pass)= 3.5 %
P(Attendance > 80%)= 43.5 %
P(Group Discussion = Yes)= 71.5 %

# 2. Types of Events

## Empirical Probability

Empirical probability is calculated using actual observed data or past observations.

Formula:

P(E) = Number of times event occurs / Total number of observations

we will calculate the empirical probability of a student passing the final exam.

In [71]:
pass_count = (df["final_exam_pass"] == "Pass").sum()
total_students = len(df)

empirical_probability = pass_count / total_students

print("Number of students who passed:", pass_count)
print("Total students:", total_students)
print("Empirical Probability of Passing:", empirical_probability)
print("Empirical Probability (%):", round(empirical_probability * 100, 2), "%")

Number of students who passed: 7
Total students: 200
Empirical Probability of Passing: 0.035
Empirical Probability (%): 3.5 %

## Theoretical Probability

Theoretical probability is the probability of an event calculated based on the possible outcomes, without actually performing the experiment.

### Formula

$$
P(E)=\frac{\text{Number of Favorable Outcomes}}{\text{Total Number of Possible Outcomes}}
$$

# 3. Random Variable & Probability Distribution

Let X be the number of students who pass the final exam out of 3 randomly selected students.

Therefore, the possible values of X are:

X = 0, 1, 2, 3

In [72]:
from math import comb

n = 3
p = empirical_probability
q = 1 - p

x_values = [0, 1, 2, 3]

probabilities = []

for k in x_values:
    prob = comb(n, k) * (p ** k) * (q ** (n - k))
    probabilities.append(prob)

distribution = pd.DataFrame({
    "X (Number of Pass Students)": x_values,
    "P(X)": probabilities
})

distribution

   X (Number of Pass Students)      P(X)
0                            0  0.898632
1                            1  0.097779
2                            2  0.003546
3                            3  0.000043

#### Check Probabilty total

In [73]:
distribution["P(X)"].sum()

np.float64(0.9999999999999999)

### Mean of the Random Variable

The mean of a discrete random variable is calculated as:

E(X) = Σ [x × P(X = x)]

It represents the expected number of students who will pass out of 3 randomly selected students.

In [74]:
mean_x = (distribution["X (Number of Pass Students)"] * distribution["P(X)"]).sum()

print("Mean (Expected Number of Pass Students):", mean_x)

Mean (Expected Number of Pass Students): 0.105

### Variance of the Random Variable

Variance measures how much the values of the random variable vary around its mean.

Formula:

Var(X) = Σ [ (x - μ)² × P(X = x) ]

In [75]:
variance_x = (
    (
        distribution["X (Number of Pass Students)"] - mean_x
    ) ** 2
    * distribution["P(X)"]
).sum()

print("Variance:", variance_x)

Variance: 0.101325

# 4. Venn Diagram

Let:

- A = Students who study for more than 10 hours
- B = Students whose attendance is greater than 80%
- C = Overlap showing students who satisfy both conditions.

The Venn diagram will show:

- A only
- B only
- C = A ∩ B (both conditions)
- Neither A nor B

In [76]:
A = df["study_hours"] > 10
B = df["attendance"] > 80

A_only = (A & ~B).sum()
B_only = (~A & B).sum()
intersection = (A & B).sum()
neither = (~A & ~B).sum()

print("A only:", A_only)
print("B only:", B_only)
print("C = A ∩ B (both condtition):", intersection)
print("Neither:", neither)

A only: 40
B only: 46
C = A ∩ B (both condtition): 41
Neither: 73

#### Check total

In [77]:
A_only+B_only+intersection+neither

np.int64(200)

# 5. Contingency Table & Probability

A contingency table shows the relationship between two categorical variables.

Here we compare:
- Group Discussion: Yes / No
- Final Exam: Pass / Fail

In [78]:
contingency_table = pd.crosstab(
    df["group_discussion"],
    df["final_exam_pass"]
)

contingency_table

final_exam_pass   Fail  Pass
group_discussion
no                  57     0
yes                136     7

## Joint Probability

Joint probability is the probability that two events occur together.

Formula:

P(A ∩ B) = Number of observations satisfying both events / Total observations

In [79]:
joint_probability = contingency_table / len(df)

joint_probability

final_exam_pass    Fail   Pass
group_discussion
no                0.285  0.000
yes               0.680  0.035

## Marginal Probability

Marginal probability is the probability of one variable without considering the other variable.

In [80]:
marginal_group = df["group_discussion"].value_counts(normalize=True)
marginal_pass = df["final_exam_pass"].value_counts(normalize=True)

In [81]:
print("Marginal Probability - Group Discussion")
print(marginal_group)

Marginal Probability - Group Discussion
group_discussion
yes    0.715
no     0.285
Name: proportion, dtype: float64

In [82]:

print("\nMarginal Probability - Final Exam")
print(marginal_pass)

Marginal Probability - Final Exam
final_exam_pass
Fail    0.965
Pass    0.035
Name: proportion, dtype: float64

## Conditional Probability

Conditional probability is the probability of an event occurring given that another event has already occurred.

For example:

P(Pass | Group Discussion = Yes)

In [83]:
p_pass_given_discussion = (
    df[df["group_discussion"] == "Yes"]["final_exam_pass"]
    .eq("Pass")
    .mean()
)

print(
    "P(Pass | Group Discussion = Yes) =",
    p_pass_given_discussion
)

P(Pass | Group Discussion = Yes) = nan

# 6. Understanding Relationships

The relationship between Group Discussion and Final Exam Pass is analyzed using conditional probability.

If the probability of passing changes depending on whether a student participates in group discussion, the two events may be dependent.

If the probabilities remain the same, the events may be independent.

In [84]:
p_pass = (df["final_exam_pass"] == "Pass").mean()

In [85]:
p_pass_given_yes = (
    df[df["group_discussion"] == "Yes"]["final_exam_pass"]
    .eq("Pass")
    .mean()
)

In [86]:
p_pass_given_no = (
    df[df["group_discussion"] == "No"]["final_exam_pass"]
    .eq("Pass")
    .mean()
)

In [87]:
print("P(Pass) =", p_pass)
print("P(Pass | Group Discussion = Yes) =", p_pass_given_yes)
print("P(Pass | Group Discussion = No) =", p_pass_given_no)

P(Pass) = 0.035
P(Pass | Group Discussion = Yes) = nan
P(Pass | Group Discussion = No) = nan

## Relationship Interpretation

If P(Pass | Group Discussion = Yes) is different from P(Pass), this suggests that the two events are dependent.

If P(Pass | Group Discussion = Yes) is approximately equal to P(Pass), this suggests independence.

Group Discussion = Yes and Final Exam = Pass are not mutually exclusive because both events can occur for the same student.

# 7. Bayes Theorem

Bayes Theorem is used to calculate the probability of an event based on prior information.

Formula:

P(A|B) = [P(B|A) × P(A)] / P(B)

Given:

P(H|Pass) = 0.70
P(H|Fail) = 0.40
P(H) = 0.60

Find:

P(Pass|H)

In [88]:
p_h_given_pass = 0.70
p_h_given_fail = 0.40
p_h = 0.60

In [89]:
p_pass = (p_h - p_h_given_fail) / (p_h_given_pass - p_h_given_fail)
p_fail = 1 - p_pass

In [90]:
p_pass_given_h = (p_h_given_pass * p_pass) / p_h

In [91]:
print("P(Pass) =", p_pass)
print("P(Fail) =", p_fail)
print("P(Pass | H) =", p_pass_given_h)
print("P(Pass | H) (%) =", round(p_pass_given_h * 100, 2), "%")

P(Pass) = 0.6666666666666666
P(Fail) = 0.33333333333333337
P(Pass | H) = 0.7777777777777777
P(Pass | H) (%) = 77.78 %

## Interpretation

Based on the given probabilities and Bayes Theorem, the probability of Pass given H is 75%.

Therefore:

P(Pass | H) = 0.75

# Final Summary

The probability analysis was performed using the student dataset.

- The probability of passing the final exam was calculated using empirical probability.
- Theoretical probability was calculated using a Binomial Probability Distribution for 3 randomly selected students.
- The mean and variance of the random variable were calculated.
- A Venn diagram was used to analyze students with study hours greater than 10 and attendance greater than 80%.
- A contingency table was created to analyze Group Discussion and Final Exam results.
- Joint, marginal, and conditional probabilities were calculated.
- The relationship between Group Discussion and Final Exam Pass was analyzed using conditional probability.
- Bayes Theorem was applied to calculate P(Pass | H), which was 75% based on the given values.